version: "3.7"

services:
  mysql:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - "mysql:db"
    ports:
      - 8081:80

volumes:
  mysql-volume:
